apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-acme
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-acme
subjects:
  - name: openshift-acme
    kind: ServiceAccount
