apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    kubernetes.io/tls-acme: 'true'
  name: cloudplus
  labels:
    visibility: internet
spec:
  host: cloudplus.multicloud.ovh
  to:
    kind: Service
    name: myservicename
